#! /usr/bin/bash
source ./configure_deck_create_zenity.sh running

tasks_to_run='echo "33.00"
echo "# interaction_install_proton_ge_in_steam"
interaction_install_proton_ge_in_steam
echo "66.00"
echo "# install_proton_ge_in_steam"
install_proton_ge_in_steam
echo "100.00"
echo "# install_bauh"
install_bauh'

echo "$tasks_to_run" | zenity --progress